### ISSUE TITLE
Markup instead of tables in the output

### ISSUE THREAD

**Issue by delameter** [sebastiancarlos/manpdf#3]
**Describe the bug**
Markup instead of tables in the output

![image](https://user-images.githubusercontent.com/50381946/230873887-47342fe9-2a49-4c8b-870a-ed3abb8cd477.png)

**To Reproduce**
Generate PDF out of man page containing a table, e.g. ```manpdf systemd.unit```

**Expected behavior**
Table similar to the source

![image](https://user-images.githubusercontent.com/50381946/230874284-2447c26f-b85d-48a6-a794-2e677001eb87.png)

**Environment (please complete the following information):**
 - OS: ```Ubuntu 20.04.5 LTS 64-bit```
 - Version (`mandb --version`): ```mandb 2.9.1```
 - Groff version (`groff --version`):  ```GNU groff version 1.22.4```

**Additional context**
systemd version is `245`

**Comment by sebastiancarlos** [comment]
Thanks for the report. This should be fixed on the latest version. Feel free to reopen if the problem persists.

By the way, the table on page 21, called "Table 4. Specifiers available in unit files" is not rendering at all because it doesn't fit in the page. I think this can be fixed upstream, so I opened [an issue](https://github.com/systemd/systemd/issues/27213) on systemd.
