### ISSUE TITLE
Project duplicates existing man functionality

### ISSUE THREAD

**Issue by KernelFrog** [sebastiancarlos/manpdf#5]
This project appears to duplicate the functionality provided by
 `man -Tpdf`

Suggest project be deprecated.

**Comment by sebastiancarlos** [comment]
Many features of this project are not possible with `man -Tpdf`. Case in point, the functionality offered by the `man-web` command is not possible with `man -Tpdf` because, as far as I understand, the `man` command has no capability to fetch man pages from the internet.

I invite you to go through all the features of this project and explain how each of them are replicated by `man -Tpdf`. If you do so, I will happily deprecate the repo. For the time being, I'll close the issue.
